### ISSUE TITLE
Maybe good to have following features and have some glitch bugs

### ISSUE THREAD

**Issue by themisir** [mastorak/caveempire#1]
> Game save & load
> New levels (Game restarted when I completed the level)

**Comment by mastorak** [comment]
Hi, thank you for your interest in this. I appreciate it.
This project was part of the Github Game Off 2018 1-month game jam. I am not currently planning to work on this in the near future as it was created specifically for the jam. 
If I work on this in future, things that need to be fixed include: 
- path finding
- ranged attack when on a ramp
- unit selection precision
- speed up build time for certain units
- create more levels
- port codebase to godot 3.1
- camera limits

If enough interest exists in the future I 'll try(and possibly fail) to find the time. Of course everyone is welcome to fix things and create new levels :-)
